FROM odoo:18.0

WORKDIR /usr/lib/python3/dist-packages/odoo

ENV DB_HOST=$DB_HOST \
DB_PORT=$DB_PORT \
DB_USER=$DB_USER \
DB_PASSWORD=$DB_PASSWORD

EXPOSE 8069

CMD ["odoo", "-c", "/etc/odoo/odoo.conf"]
